config/routes.rb
Rails.application.routes.draw do
  resources :fb_ads, path: 'ads', only: [:index, :new, :create]
  get '/ads/:id/run', to: 'fb_ads#run', as: :run_fb_ad
  post '/update_interests', to: 'fb_ads#update_interests'

  resources :settings, only: [:edit, :update], controller: 'home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get 'privacy', to: 'home#privacy'

  root to: "home#index"
end

app/models/fb_ad.rb
class FbAd < ApplicationRecord
  validates :uid, presence: true
  validates :campaign_name, presence: true
  validates :gender, presence: true
  validates :headline, presence: true
  validates :ptext, presence: true
  validates :video_url, presence: true
  validates :thumbnail_url, presence: true
  validates :pixel_id, presence: true
  # validates :interests, presence: true, length: { minimum: 4, too_short: ": select at least one." }
  # validates :countries, presence: true, length: { minimum: 4, too_short: ": select at least one." }
  validate :at_least_one_interest, :at_least_one_country

  def at_least_one_country
    if (JSON.parse countries).empty?
      errors.add(:countries, "must be one or more")
    end
  end

  def at_least_one_interest
    if (JSON.parse interests).empty?
      errors.add(:interests, "must be one or more")
    end
  end

end

app/controllers/fb_ads_controller.rb
class FbAdsController < ApplicationController
  before_action :require_login
  before_action :set_fb_ad, only: [:run]
  before_action :set_ad_acct_query, only: [:run, :update_interests]

  # GET /ads
  def index
    @fb_ads = FbAd.where(uid: current_user.uid)
  end

  # # GET /ads/1
  # def show
  # end

  # GET /ads/new
  def new
    @fb_ad = FbAd.new
  end

  # # GET /ads/1/edit
  # def edit
  # end

  def update_interests
    @interests = @ad_acct_query.targetingsearch({
      q: params[:suggestion],
      type: 'adinterest',
      fields: 'name,id,audience_size'
    }).first(10)

    render json: @interests
  end

  # POST /ads
  def create
    # Create an empty FbAd a fill it with the form info
    @fb_ad = FbAd.new(fb_ad_params)

    @fb_ad.uid = current_user.uid
    # Time when to publish this ad.
    # NOTE this is a tentative date, from the original code. When this ad is
    # 'run' (see fb_ads#run) it will update the start_time.
    # 60 seconds * 60 minutes * 24 hours = 86400 seconds/day
    tomorrow = Time::now + 86400
    @fb_ad.start_time = tomorrow

    # Create and send the video to FB
    video = {
      name: "Video File #{Random.rand(300)}",
      file_url: fb_ad_params[:video_url]
    }

    begin
      created_video = current_user.ad_acct_query.advideos.create(video)

      # Add to the new FbUser the params that were not set in the form
      @fb_ad.video_id = created_video.id
    rescue FacebookAds::ClientError => e
      flash.now[:alert] = e.error_user_title
      render :new
      return
    end

    respond_to do |format|
      if @fb_ad.save
        format.html { redirect_to fb_ads_url, notice: 'Fb ad was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # # PATCH/PUT /ads/1
  # def update
  #   respond_to do |format|
  #     if @fb_ad.update(fb_ad_params)
  #       format.html { redirect_to @fb_ad, notice: 'Fb ad was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @fb_ad }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @fb_ad.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /ads/1
  # def destroy
  #   @fb_ad.destroy
  #   respond_to do |format|
  #     format.html { redirect_to fb_ads_url, notice: 'Fb ad was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  # POST /ads/1/run
  def run


    AdsRunJob.perform_later @fb_ad, current_user

    @fb_ad.update({
      result_status: 'Pending.'
    })

    respond_to do |format|
      format.html { redirect_to fb_ads_path, notice: 'Fb ad is pending to be created.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fb_ad
      @fb_ad = FbAd.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fb_ad_params
      params[:fb_ad][:countries] = params[:fb_ad][:countries].reject {|c| c.empty?}
      params[:fb_ad][:interests] = params[:fb_ad][:interests].reject {|c| c.empty?}
      params.require(:fb_ad).permit(:campaign_name, :gender, :headline, :ptext,
                                    :video_url, :thumbnail_url, :pixel_id,
                                    :interests => [], :countries => [])
    end

    # Handy function
    def set_ad_acct_query
      # @ad_acct_query = FacebookAds::AdAccount.get(current_user.ad_account_id, 'name', current_user.fb_session)
      @ad_acct_query = current_user.ad_acct_query
    end
end

app/helpers/fb_ads_helper.rb
module FbAdsHelper
  def countries_list
    # Should probably use something like: https://rubygems.org/gems/iso_3166
    countries = [
      ["Australia",     "AU"], ["Austria",     "AT"], ["Belgium",        "BE"],
      ["Brazil",        "BR"], ["Canada",      "CA"], ["Croatia",        "HR"],
      ["Denmark",       "DK"], ["Estonia",     "EE"], ["Finland",        "FI"],
      ["France",        "FR"], ["Germany",     "DE"], ["Gibraltar",      "GI"],
      ["Great Britian", "GB"], ["Greece",      "GR"], ["Hong Kong",      "HK"],
      ["Hungary",       "HU"], ["Ireland",     "IE"], ["Israel",         "IL"],
      ["Italy",         "IT"], ["Japan",       "JP"], ["Latvia",         "LV"],
      ["Lithuania",     "LT"], ["Luxembourg",  "LU"], ["Malaysia",       "MY"],
      ["Malta",         "MT"], ["Mexico",      "MX"], ["Netherlands",    "NL"],
      ["New Zealand",   "NZ"], ["Norway",      "NO"], ["Poland",         "PL"],
      ["Portugal",      "PT"], ["Russia",      "RU"], ["Saudi Arabia",   "SA"],
      ["Singapore",     "SG"], ["Spain",       "ES"], ["South Korea",    "KR"],
      ["Sweden",        "SE"], ["Switzerland", "CH"], ["Thailand",       "TH"],
      ["Turkey",        "TR"], ["Ukraine",     "UA"], ["United Kingdom", "GB"],
      ["United States", "US"], ["Vietnam",     "VN"]
    ]

    return countries
  end
end

app/views/fb_ads/_form.html.erb
<%= form_with(model: fb_ad, url: fb_ads_path, local: true) do |form| %>
  <% if fb_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fb_ad.errors.count, "error") %> prohibited this fb_ad from being saved:</h2>

      <ul>
        <% fb_ad.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :campaign_name %>
    <%= form.text_field :campaign_name, placeholder: "Enter the Product name" %>
  </div>

  <div class="field">
    <%= label_tag :interests_text %>
    <%= text_field_tag :interests_text, nil, placeholder: "Search for interests" %>
  </div>

  <div class="field">
    <%= form.label :interests %>
    <%= select :fb_ad, :interests, options_for_select([]), {}, { multiple: true, size: 10 } %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= select(:fb_ad, :gender, options_for_select([['Both', 0], ['Male', 1], ['Female', 2]])) %>
  </div>

  <div class="field">
    <%= form.label :headline %>
    <%= form.text_field :headline, placeholder: "Enter the Headline" %>
  </div>

  <div class="field">
    <%= form.label :ptext %>
    <%= form.text_field :ptext, placeholder: "Enter your Primary Text" %>
  </div>

  <div class="field">
    <%= form.label :video_url %>
    <%= form.text_field :video_url, placeholder: "Enter a downloadable link" %>
  </div>

  <div class="field">
    <%= form.label :thumbnail_url %>
    <%= form.text_field :thumbnail_url, placeholder: "Enter the thumbnail URL" %>
  </div>

  <div class="field">
    <%= form.label :pixel_id %>
    <%= select(:fb_ad, :pixel_id, options_for_select(current_user.ad_acct_query.adspixels(fields: 'name,id').map {|p| [p.name, p.id]})) %>
  </div>

  <div class="field">
    <%= form.label :countries %>
    <%= select :fb_ad, :countries, options_for_select(countries_list), {}, { multiple: true, size: 10 } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fb_ads/edit.html.erb
<h1>Editing Fb Ad</h1>

<%= render 'form', fb_ad: @fb_ad %>

<%= link_to 'Show', @fb_ad %> |
<%= link_to 'Back', fb_ads_path %>

app/views/fb_ads/index.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<h1>Fb Ads</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Campaign name</th>
      <th>Campaign id</th>
      <th>Ad set id</th>
      <th>Interests</th>
      <th>Gender</th>
      <th>Ad Creative</th>
      <th>Headline</th>
      <th>Ptext</th>
      <th>Video url</th>
      <th>Thumbnail url</th>
      <th>Countries</th>
      <th>Result</th>
      <th>Ad id</th>
      <th>Start time</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @fb_ads.each do |fb_ad| %>
      <tr>
        <td><%= fb_ad.id %></td>
        <td><%= fb_ad.campaign_name %></td>
        <td><%= fb_ad.campaign_id %></td>
        <td><%= fb_ad.ad_set_id %></td>
        <td><%= fb_ad.interests %></td>
        <td><%= fb_ad.gender %></td>
        <td><%= fb_ad.creative_id %></td>
        <td><%= fb_ad.headline %></td>
        <td><%= fb_ad.ptext %></td>
        <td><%= fb_ad.video_url %></td>
        <td><%= fb_ad.thumbnail_url %></td>
        <td><%= fb_ad.countries %></td>
        <td><%= fb_ad.result %></td>
        <td><%= fb_ad.ad_id %></td>
        <td><%= fb_ad.start_time %></td>
        <td><%= link_to 'Run', run_fb_ad_url(fb_ad) %></td>
        <%# <td><%= link_to 'Show', fb_ad %1></td> %>
        <%# <td><%= link_to 'Edit', edit_fb_ad_path(fb_ad) %1></td> %>
        <%# <td><%= link_to 'Destroy', fb_ad, method: :delete, data: { confirm: 'Are you sure?' } %1></td> %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fb Ad', new_fb_ad_path %>

app/views/fb_ads/new.html.erb
<%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
<%= javascript_pack_tag 'dynamic_interests' %>
<h1>New Fb Ad</h1>
<p id="alert"><%= alert %></p>

<%= render 'form', fb_ad: @fb_ad %>

<%= link_to 'Back', fb_ads_path %>

app/views/fb_ads/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<p>
  <strong>Uid:</strong>
  <%= @fb_ad.uid %>
</p>

<p>
  <strong>Campaign name:</strong>
  <%= @fb_ad.campaign_name %>
</p>

<p>
  <strong>Interests:</strong>
  <%= @fb_ad.interests %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @fb_ad.gender %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @fb_ad.headline %>
</p>

<p>
  <strong>Ptext:</strong>
  <%= @fb_ad.ptext %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @fb_ad.video_url %>
</p>

<p>
  <strong>Thumbnail url:</strong>
  <%= @fb_ad.thumbnail_url %>
</p>

<p>
  <strong>Video:</strong>
  <%= @fb_ad.video_id %>
</p>

<p>
  <strong>Pixel:</strong>
  <%= @fb_ad.pixel_id %>
</p>

<p>
  <strong>Countries:</strong>
  <%= @fb_ad.countries %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @fb_ad.start_time %>
</p>

<%= link_to 'Edit', edit_fb_ad_path(@fb_ad) %> |
<%= link_to 'Back', fb_ads_path %>