config/routes.rb
Rails.application.routes.draw do
  resources :fb_ads, path: 'ads', only: [:index, :new, :create]
  get '/ads/:id/run', to: 'fb_ads#run', as: :run_fb_ad
  post '/update_interests', to: 'fb_ads#update_interests'

  resources :settings, only: [:edit, :update], controller: 'home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get 'privacy', to: 'home#privacy'

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login, only: [:edit, :update]
  before_action :set_fb_user, only: [:edit, :update]

  def index
  end

  # GET /edit
  def edit
    @ad_accounts = @fb_user.u_query.adaccounts(fields: 'name,id').map {|a| [a.name, a.id]}
    @pages = @fb_user.u_query.accounts(fields: 'name,id').map {|p| [p.name, p.id]}
  end

  # PATCH/PUT /edit
  def update
    respond_to do |format|
      if @fb_user.update(fb_user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def privacy
  end

  private

  def set_fb_user
    @fb_user = FbUser.find(session[:user_id])
  end

  def fb_user_params
    params.require(:fb_user).permit(:ad_account_id, :page_id, :url)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/edit.html.erb
<h1>Editing User</h1>

<%= form_with(model: @fb_user, url: setting_path, method: 'patch', local: true) do |form| %>
  <% if @fb_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fb_user.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
        <% @fb_user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ad_account_id %>
    <%= select :fb_user, :ad_account_id, options_for_select(@ad_accounts) %>
  </div>

  <%# <div class="field"> %>
  <%#   <%= form.label :pixel_id %1> %>
  <%#   <%= select_tag :pixel_id, options_for_select(@pixels) %1> %>
  <%# </div> %>

  <div class="field">
    <%= form.label :page_id %>
    <%= select :fb_user, :page_id, options_for_select(@pages) %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', root_path %>

app/views/home/index.html.erb
<h1>FB Ads Portal</h1>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="well well-sm">
                <legend class="text-center">Welcome to Ads Portal</legend>
                <div class="text-center">
                  <p id="notice"><%= notice %></p>
                    <div id="user_nav">
                      <% if current_user %>
                        Signed in as <strong><%= current_user.name %></strong>!
                        User token <strong><%= current_user.token %></strong>!
                        Ad Account id <strong><%= current_user.ad_account_id %></strong>!
                        <br>
                        <%= link_to "Create Ad", new_fb_ad_path, id: "create_ad" %>
                        <br>
                        <%= link_to "List ads", fb_ads_path, id: "list_ads" %>
                        <br>
                        <%= link_to "Settings", edit_setting_path(current_user), id: "settings" %>
                        <br>
                        <%= link_to "Sign out", signout_path, id: "sign_out" %>
                        <br>
                        <br>
                        <%= link_to "Privacy Policy", privacy_path, id: "privacy" %>
                      <% else %>
                        Please login and authenticate to continue.
                        <br>
                        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", class: "btn btn-primary" %>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/privacy.html.erb
<strong>Privacy Policy</strong> <p>
  Ivan G built the ads-rails app as
  an Open Source app. This SERVICE is provided by
  Ivan G at no cost and is intended for use as
  is.
</p> <p>
  This page is used to inform visitors regarding my
  policies with the collection, use, and disclosure of Personal
  Information if anyone decided to use my Service.
</p> <p>
  If you choose to use my Service, then you agree to
  the collection and use of information in relation to this
  policy. The Personal Information that I collect is
  used for providing and improving the Service. I will not use or share your information with
  anyone except as described in this Privacy Policy.
</p> <p>
  The terms used in this Privacy Policy have the same meanings
  as in our Terms and Conditions, which is accessible at
  ads-rails unless otherwise defined in this Privacy Policy.
</p> <p><strong>Information Collection and Use</strong></p> <p>
  For a better experience, while using our Service, I
  may require you to provide us with certain personally
  identifiable information, including but not limited to name, email, page_id, ad_account_id. The information that
  I request will be retained on your device and is not collected by me in any way.
</p> <div><p>
    The app does use third party services that may collect
    information used to identify you.
  </p> <p>
    Link to privacy policy of third party service providers used
    by the app
  </p> <ul><li><a href="https://www.google.com/policies/privacy/" target="_blank">Google Play Services</a></li><!----><!----><!----><li><a href="https://www.facebook.com/about/privacy/update/printable" target="_blank">Facebook</a></li><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----><!----></ul></div> <p><strong>Log Data</strong></p> <p>
  I want to inform you that whenever you
  use my Service, in a case of an error in the app
  I collect data and information (through third party
  products) on your phone called Log Data. This Log Data may
  include information such as your device Internet Protocol
  (“IP”) address, device name, operating system version, the
  configuration of the app when utilizing my Service,
  the time and date of your use of the Service, and other
  statistics.
</p> <p><strong>Cookies</strong></p> <p>
  Cookies are files with a small amount of data that are
  commonly used as anonymous unique identifiers. These are sent
  to your browser from the websites that you visit and are
  stored on your device's internal memory.
</p> <p>
  This Service does not use these “cookies” explicitly. However,
  the app may use third party code and libraries that use
  “cookies” to collect information and improve their services.
  You have the option to either accept or refuse these cookies
  and know when a cookie is being sent to your device. If you
  choose to refuse our cookies, you may not be able to use some
  portions of this Service.
</p> <p><strong>Service Providers</strong></p> <p>
  I may employ third-party companies and
  individuals due to the following reasons:
</p> <ul><li>To facilitate our Service;</li> <li>To provide the Service on our behalf;</li> <li>To perform Service-related services; or</li> <li>To assist us in analyzing how our Service is used.</li></ul> <p>
  I want to inform users of this Service
  that these third parties have access to your Personal
  Information. The reason is to perform the tasks assigned to
  them on our behalf. However, they are obligated not to
  disclose or use the information for any other purpose.
</p> <p><strong>Security</strong></p> <p>
  I value your trust in providing us your
  Personal Information, thus we are striving to use commercially
  acceptable means of protecting it. But remember that no method
  of transmission over the internet, or method of electronic
  storage is 100% secure and reliable, and I cannot
  guarantee its absolute security.
</p> <p><strong>Links to Other Sites</strong></p> <p>
  This Service may contain links to other sites. If you click on
  a third-party link, you will be directed to that site. Note
  that these external sites are not operated by me.
  Therefore, I strongly advise you to review the
  Privacy Policy of these websites. I have
  no control over and assume no responsibility for the content,
  privacy policies, or practices of any third-party sites or
  services.
</p> <p><strong>Children’s Privacy</strong></p> <p>
  These Services do not address anyone under the age of 13.
  I do not knowingly collect personally
  identifiable information from children under 13. In the case
  I discover that a child under 13 has provided
  me with personal information, I immediately
  delete this from our servers. If you are a parent or guardian
  and you are aware that your child has provided us with
  personal information, please contact me so that
  I will be able to do necessary actions.
</p> <p><strong>Changes to This Privacy Policy</strong></p> <p>
  I may update our Privacy Policy from
  time to time. Thus, you are advised to review this page
  periodically for any changes. I will
  notify you of any changes by posting the new Privacy Policy on
  this page.
</p> <p>This policy is effective as of 2020-05-03</p> <p><strong>Contact Us</strong></p> <p>
  If you have any questions or suggestions about my
  Privacy Policy, do not hesitate to contact me at ivan14polanco@gmail.com.
</p> <p>
  This privacy policy page was created at
  <a href="https://privacypolicytemplate.net" target="_blank">privacypolicytemplate.net</a>
  and modified/generated by
  <a href="https://app-privacy-policy-generator.firebaseapp.com/" target="_blank">App Privacy Policy Generator</a></p>